---
- name: Generate configuration files
  template: src=access_switch.j2 dest=/home/gsharpe/git_repos/pynet_network_automation_course/week5/q1_ansible/roles/access_switch/templates/{{item.hostname}}.txt
  with_items: "{{ access_switches }}"
