access_switches:
  - { hostname: twb-sf-sw1, secret: some_password, access_vlan: 10, ip_addr: 10.10.10.10, default_gateway: 10.10.10.1, snmp_community: blah_comm, SNMPv3: true }
  - { hostname: twb-sf-sw2, secret: some_password, access_vlan: 10, ip_addr: 10.10.10.11, default_gateway: 10.10.10.1, snmp_community: blah_comm, SNMPv3: true }

cisco_3750_l2_interfaces:
 - FastEthernet0/1
 - FastEthernet0/2
 - FastEthernet0/3
 - FastEthernet0/4
 - FastEthernet0/5
 - FastEthernet0/6
 - FastEthernet0/7
 - FastEthernet0/8
 - FastEthernet0/9
 - FastEthernet0/10
 - FastEthernet0/11
 - FastEthernet0/12
 - FastEthernet0/13
 - FastEthernet0/14
 - FastEthernet0/15
 - FastEthernet0/16
 - FastEthernet0/17
 - FastEthernet0/18
 - FastEthernet0/19
 - FastEthernet0/20
 - FastEthernet0/21
 - FastEthernet0/22
 - FastEthernet0/23
 - FastEthernet0/24
